services:
  dream-league-finance-api:
    build: .
    image: dream-league-finance-api
    container_name: dream-league-finance-api
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://dream-league-finance-mongo:27017/dream-league-finance
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY_IN_MINUTES=${JWT_EXPIRY_IN_MINUTES}
      - WEB_URL=${WEB_URL}
      - WINNERS_API_URL=${WINNERS_API_URL}
      - ALLOW_NON_MEMBER_REGISTRATION=${ALLOW_NON_MEMBER_REGISTRATION}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - dream-league-finance-mongo
    networks:
      - dream-league-finance-network
    restart: unless-stopped

  dream-league-finance-mongo:
    image: mongo:7
    container_name: dream-league-finance-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - dream-league-finance-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  dream-league-finance-network:
    name: dream-league-finance-network
